extends Node


var powerups_pool = [
	"res://weapons/pistol/pistol_powerup.tscn",
	"res://weapons/shotgun/shotgun_power_up.tscn",
	"res://weapons/shotgun_fire/shotgun_fire_power_up.tscn",
	"res://weapons/rifle/rifle_power_up.tscn",
	"res://weapons/minigun/minigun_power_up.tscn",
	"res://weapons/railgun/railgun_power_up.tscn",
	"res://weapons/rocket_launcher/rocket_launcher_power_up.tscn",
	"res://weapons/lasergun/laser_gun_power_up.tscn",
	"res://weapons/laser_shotgun/laser_shotgun_power_up.tscn",
	"res://weapons/grenade_launcher/grenade_launcher_power_up.tscn",
	"res://weapons/laser_minigun/laser_minigun_power_up.tscn",
	"res://weapons/plasma_minigun/plasma_minigun_power_up.tscn",
	"res://weapons/plasma_shotgun/plasma_shotgun_power_up.tscn",
	"res://weapons/plasmagun/plasma_gun_power_up.tscn",
	"res://weapons/flamethrower/flamethrower_power_up.tscn",
	"res://weapons/gas_gun/gas_gun_power_up.tscn",
	"res://weapons/wave_rifle/wave_rifle_powerup.tscn",
	"res://weapons/bullet_split_gun/spliting_bullet_gun_item.tscn",
	"res://weapons/laser_beamer/laser_beamer_item.tscn",
	"res://weapons/the_maul/the_maul_gun_powerup.tscn",
	"res://weapons/railbow_beamer/rainbow_beamer_item.tscn",
	"res://weapons/electric_weapon/electric_weapon_powerup.tscn",
	"res://weapons/missile_launcher/missile_launcher_item.tscn",
	"res://weapons/money_gun/money_gun_item.tscn",
	"res://powerups/damage/damage_power_up.tscn",
	"res://powerups/guns_attack_speed/guns_attack_speed_power_up.tscn",
	"res://powerups/hp_regen/hp_regen_power_up.tscn",
	"res://powerups/max_hp/max_hp_power_up.tscn",
	"res://powerups/range/range_power_up.tscn",
	"res://support_weapons/bombs/bombs_power_up.tscn",
	"res://support_weapons/bomb_plane/bomb_plane_powerup.tscn",
	"res://powerups/force_field/force_field_powerup.tscn",
	"res://powerups/time_slow_down/time_slowdown_powerup.tscn",
	"res://powerups/offensive_force_field/offensive_force_field.tscn",
]
