extends Node


var pistol_scene = preload("res://weapons/pistol/pistol.tscn")
var shotgun_scene = preload("res://weapons/shotgun/shotgun.tscn")
var shotgun_fire_scene = preload("res://weapons/shotgun_fire/shotgun_fire.tscn")
var rifle_scene = preload("res://weapons/rifle/rifle.tscn")
var minigun_scene = preload("res://weapons/minigun/minigun.tscn")
var railgun_scene = preload("res://weapons/railgun/railgun.tscn")
var rocket_launcher_scene = preload("res://weapons/rocket_launcher/rocket_launcher.tscn")
var laser_gun_scene = preload("res://weapons/lasergun/laser_gun.tscn")
var laser_shotgun_scene = preload("res://weapons/laser_shotgun/laser_shotgun.tscn")
var grenade_launcher_scene = preload("res://weapons/grenade_launcher/grenade_launcher.tscn")
var laser_minigun_scene = preload("res://weapons/laser_minigun/laser_minigun.tscn")
var plasma_minigun_scene = preload("res://weapons/plasma_minigun/plasma_minigun.tscn")
var plasma_shotgun_scene = preload("res://weapons/plasma_shotgun/plasma_shotgun.tscn")
var plasma_gun_scene = preload("res://weapons/plasmagun/plasma_gun.tscn")
var flamethrower = preload("res://weapons/flamethrower/flamethrower.tscn")
var gas_gun = preload("res://weapons/gas_gun/gas_gun.tscn")
var wave_rifle = preload("res://weapons/wave_rifle/wave_rifle.tscn")
var spliting_bullet_gun = preload("res://weapons/bullet_split_gun/spliting_bullet_gun.tscn")
var laser_beamer = preload("res://weapons/laser_beamer/laser_beamer.tscn")
var the_maul = preload("res://weapons/the_maul/the_maul_gun.tscn")
var rainbow_beamer = preload("res://weapons/railbow_beamer/rainbow_beamer.tscn")
var electric_weapon = preload("res://weapons/electric_weapon/electric_weapon.tscn")
var missile_launcher = preload("res://weapons/missile_launcher/missile_launcher.tscn")
var money_gun = preload("res://weapons/money_gun/money_gun.tscn")
